M48
; DRILL file {KiCad 9.0.5} date 2025-10-31T02:29:56+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-31T02:29:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0610
%
G90
G05
T1
X0.2404Y0.9996
X0.2404Y0.772
T2
X1.1772Y0.622
T3
X1.1772Y1.4094
M30
